/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nci_utils_Helper */

#ifndef _Included_com_nci_utils_Helper
#define _Included_com_nci_utils_Helper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nci_utils_Helper
 * Method:    getAge
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_nci_utils_Helper_getAge
  (JNIEnv *, jclass, jobject);
JNIEXPORT void JNICALL Java_com_nci_utils_Helper_getAgeByAddress
  (JNIEnv *, jclass, jlong);
#ifdef __cplusplus
}
#endif
#endif